// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Element__Inlines__Type$Guabao = require("./Element__Inlines/Element__Inlines__Type.bs.js");
var Element__Inlines__View$Guabao = require("./Element__Inlines/Element__Inlines__View.bs.js");

var ClassNames = Element__Inlines__Type$Guabao.ClassNames;

var RewriteReason = Element__Inlines__Type$Guabao.RewriteReason;

var Inline = Element__Inlines__Type$Guabao.Inline;

var string = Element__Inlines__Type$Guabao.string;

var decode = Element__Inlines__Type$Guabao.decode;

var encode = Element__Inlines__Type$Guabao.encode;

var Parens = Element__Inlines__View$Guabao.Parens;

var Parens2 = Element__Inlines__View$Guabao.Parens2;

var Sbst = Element__Inlines__View$Guabao.Sbst;

var make = Element__Inlines__View$Guabao.make;

exports.ClassNames = ClassNames;
exports.RewriteReason = RewriteReason;
exports.Inline = Inline;
exports.string = string;
exports.decode = decode;
exports.encode = encode;
exports.Parens = Parens;
exports.Parens2 = Parens2;
exports.Sbst = Sbst;
exports.make = make;
/* Element__Inlines__Type-Guabao Not a pure module */
