// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function make(param) {
  return {
          trace: []
        };
}

function push(self, undo) {
  self.trace.push(undo);
  
}

function pop(self) {
  var undo = self.trace.pop();
  if (undo !== undefined) {
    return Curry._1(undo, undefined);
  }
  
}

function isEmpty(self) {
  return self.trace.length === 0;
}

var context = React.createContext({
      trace: []
    });

var provider = context.Provider;

function Trace$Context$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: Trace$Context$Provider
};

var Context = {
  context: context,
  Provider: Provider
};

function Trace$View(Props) {
  var hidden = Props.hidden;
  var className = "element-block-code-trace" + (
    hidden ? " hidden" : ""
  );
  return React.createElement("div", {
              className: className
            }, "asdf");
}

var View = {
  make: Trace$View
};

exports.make = make;
exports.push = push;
exports.pop = pop;
exports.isEmpty = isEmpty;
exports.Context = Context;
exports.View = View;
/* context Not a pure module */
