// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function Impl(Editor) {
  var toPoint = function (param) {
    return Curry._2(Editor.Point.make, param[1] - 1 | 0, param[2] - 1 | 0);
  };
  var fromPoint = function (point, filepath) {
    return /* Pos */Caml_chrome_debugger.simpleVariant("Pos", [
              filepath,
              Curry._1(Editor.Point.line, point) + 1 | 0,
              Curry._1(Editor.Point.column, point) + 1 | 0
            ]);
  };
  var Pos = {
    toPoint: toPoint,
    fromPoint: fromPoint
  };
  var toRange = function (param) {
    if (!param) {
      return Curry._2(Editor.$$Range.make, Curry._2(Editor.Point.make, 0, 0), Curry._2(Editor.Point.make, 0, 0));
    }
    var match = param[1];
    return Curry._2(Editor.$$Range.make, toPoint(param[0]), Curry._2(Editor.Point.make, match[1] - 1 | 0, match[2]));
  };
  var Loc = {
    toRange: toRange
  };
  return {
          Pos: Pos,
          Loc: Loc
        };
}

exports.Impl = Impl;
/* No side effect */
