// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var Executable = { };

var Transport = { };

var ForkOptions = { };

function make(path, transport, args, runtime, options, param) {
  var transport$1 = Belt_Option.map(transport, (function (n) {
          if (typeof n !== "number") {
            return ({ kind: 4 , port: n });
          }
          switch (n) {
            case /* StdIO */0 :
                return 1;
            case /* IPC */1 :
                return 2;
            case /* Pipe */2 :
                return 3;
            
          }
        }));
  return {
          module: path,
          transport: transport$1,
          args: args,
          runtime: runtime,
          options: options
        };
}

var NodeModule = {
  ForkOptions: ForkOptions,
  make: make
};

var StreamInfo = { };

var ChildProcessInfo = { };

var ServerOptions = { };

var LanguageClientOptions = { };

var LanguageClient = { };

exports.Executable = Executable;
exports.Transport = Transport;
exports.NodeModule = NodeModule;
exports.StreamInfo = StreamInfo;
exports.ChildProcessInfo = ChildProcessInfo;
exports.ServerOptions = ServerOptions;
exports.LanguageClientOptions = LanguageClientOptions;
exports.LanguageClient = LanguageClient;
/* No side effect */
