// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var SynchronizeOptions = { };

function make(f, g) {
  return {
          error: (function (e, m, i) {
              var match = Curry._3(f, e, m, i);
              if (match) {
                return 2;
              } else {
                return 1;
              }
            }),
          closed: (function (param) {
              var match = Curry._1(g, undefined);
              if (match) {
                return 2;
              } else {
                return 1;
              }
            })
        };
}

var ErrorHandler = {
  make: make
};

var ConnectionOptions = { };

var LanguageClientOptions = { };

exports.SynchronizeOptions = SynchronizeOptions;
exports.ErrorHandler = ErrorHandler;
exports.ConnectionOptions = ConnectionOptions;
exports.LanguageClientOptions = LanguageClientOptions;
/* No side effect */
