// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var VSCode = require("bs-vscode/lib/js/src/VSCode.bs.js");
var Vscode = require("vscode");
var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Chan$Guabao = require("../Util/Chan.bs.js");
var VscodeLanguageclient = require("vscode-languageclient");
var Client__LSP__Binding$LanguageServerMule = require("language-server-mule/lib/js/src/Client/Client__LSP__Binding.bs.js");

var errorChan = Chan$Guabao.make(undefined);

var dataChan = Chan$Guabao.make(undefined);

function onError(callback) {
  return new Vscode.Disposable(Chan$Guabao.on(errorChan, (function (e) {
                    return Curry._1(callback, {
                                TAG: /* ConnectionError */3,
                                _0: e
                              });
                  })));
}

function onResponse(callback) {
  return new Vscode.Disposable(Chan$Guabao.on(dataChan, callback));
}

function sendRequest(self, data) {
  return $$Promise.mapError($$Promise.flatMapOk($$Promise.Js.toResult(self.client.onReady()), (function (param) {
                    return $$Promise.Js.toResult(self.client.sendRequest("guabao", data));
                  })), (function (exn) {
                return {
                        TAG: /* CannotSendRequest */4,
                        _0: exn
                      };
              }));
}

function destroy(self) {
  self.subscription.dispose();
  return $$Promise.map($$Promise.Js.toResult(self.client.stop()), (function (param) {
                
              }));
}

function make(method) {
  var serverOptions;
  switch (method.TAG | 0) {
    case /* ViaStdIO */0 :
        serverOptions = Client__LSP__Binding$LanguageServerMule.ServerOptions.makeWithCommand(method._0);
        break;
    case /* ViaTCP */1 :
        serverOptions = Client__LSP__Binding$LanguageServerMule.ServerOptions.makeWithStreamInfo(method._0, "localhost");
        break;
    case /* ViaPrebuilt */2 :
        serverOptions = Client__LSP__Binding$LanguageServerMule.ServerOptions.makeWithCommand(method._1);
        break;
    
  }
  var documentSelector = [VSCode.StringOr.others({
          language: "guabao",
          pattern: undefined,
          scheme: "file"
        })];
  var synchronize = Vscode.workspace.createFileSystemWatcher('**/.clientrc', false, false, false);
  var errorHandler = Client__LSP__Binding$LanguageServerMule.ErrorHandler.make((function (exn, _msg, _count) {
          Chan$Guabao.emit(errorChan, exn);
          return /* Shutdown */1;
        }), (function (param) {
          return /* DoNotRestart */0;
        }));
  var clientOptions = Client__LSP__Binding$LanguageServerMule.LanguageClientOptions.make(documentSelector, synchronize, errorHandler);
  var languageClient = new VscodeLanguageclient.LanguageClient("guabaoLanguageServer", "Guabao Language Server", serverOptions, clientOptions);
  var self_subscription = languageClient.start();
  var self = {
    client: languageClient,
    subscription: self_subscription,
    method: method
  };
  return $$Promise.mapError($$Promise.map($$Promise.race({
                      hd: $$Promise.Js.toResult(languageClient.onReady()),
                      tl: {
                        hd: $$Promise.map(Chan$Guabao.once(errorChan), (function (err) {
                                return {
                                        TAG: /* Error */1,
                                        _0: err
                                      };
                              })),
                        tl: /* [] */0
                      }
                    }), (function (result) {
                    if (result.TAG !== /* Ok */0) {
                      return {
                              TAG: /* Error */1,
                              _0: result._0
                            };
                    }
                    languageClient.onNotification("guabao", (function (json) {
                            return Chan$Guabao.emit(dataChan, json);
                          }));
                    return {
                            TAG: /* Ok */0,
                            _0: self
                          };
                  })), (function (e) {
                return {
                        TAG: /* ConnectionError */3,
                        _0: e
                      };
              }));
}

function getMethod(conn) {
  return conn.method;
}

var Module = {
  make: make,
  destroy: destroy,
  sendRequest: sendRequest,
  onResponse: onResponse,
  onError: onError,
  getMethod: getMethod
};

var $$Error;

var LSP;

exports.$$Error = $$Error;
exports.LSP = LSP;
exports.Module = Module;
exports.make = make;
exports.destroy = destroy;
exports.sendRequest = sendRequest;
exports.onResponse = onResponse;
exports.onError = onError;
exports.getMethod = getMethod;
/* errorChan Not a pure module */
