// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Url = require("url");
var Path = require("path");
var Curry = require("rescript/lib/js/curry.js");
var Https = require("https");
var Yauzl = require("yauzl");
var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Process = require("process");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Util$Guabao = require("../Util/Util.bs.js");
var Config$Guabao = require("../Config.bs.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

function unlink(path) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  Fs.unlink(path, (function (error) {
          if (error !== null) {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: error
                      });
          } else {
            return Curry._1(resolve, {
                        TAG: /* Ok */0,
                        _0: undefined
                      });
          }
        }));
  return match[0];
}

function rename(old, $$new) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  Fs.rename(old, $$new, (function (error) {
          if (error !== null) {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: error
                      });
          } else {
            return Curry._1(resolve, {
                        TAG: /* Ok */0,
                        _0: undefined
                      });
          }
        }));
  return match[0];
}

function readFile(path) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  Fs.readFile(path, (function (error, buffer) {
          if (error !== null) {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: error
                      });
          } else {
            return Curry._1(resolve, {
                        TAG: /* Ok */0,
                        _0: buffer
                      });
          }
        }));
  return match[0];
}

var Fs$1 = {
  unlink: unlink,
  rename: rename,
  readFile: readFile
};

var Https$1 = {};

var Url$1 = {};

var Nd = {
  Fs: Fs$1,
  Https: Https$1,
  Url: Url$1
};

function toString(x) {
  if (typeof x === "number") {
    if (x === /* NoRedirectLocation */0) {
      return "Got HTTP 301/302 from GitHub without location in headers";
    } else {
      return "Failed to unzip files";
    }
  }
  switch (x.TAG | 0) {
    case /* ResponseParseError */0 :
        return "Cannot parse release metadata from GitHub:\n" + x._0;
    case /* ResponseDecodeError */1 :
        return "Cannot decode release metadata JSON from GitHub:\n" + x._0;
    case /* ServerResponseError */2 :
        return "Server Response Error:\n" + Util$Guabao.Exn.toString(x._0);
    case /* NoMatchingVersion */3 :
        return "Cannot find " + x._0 + " in releases from GitHub";
    case /* NotSupportedOS */4 :
        return "Cannot find prebuilt for " + x._0;
    case /* CannotDeleteFile */5 :
        return "Failed to delete files:\n" + Util$Guabao.Exn.toString(x._0);
    case /* CannotRenameFile */6 :
        return "Failed to rename files:\n" + Util$Guabao.Exn.toString(x._0);
    case /* CannotWriteFile */7 :
        return "Failed to  write files:\n" + Util$Guabao.Exn.toString(x._0);
    case /* CannotUnzipFileWithExn */8 :
        return "Failed to unzip files:\n" + Util$Guabao.Exn.toString(x._0);
    
  }
}

var $$Error = {
  toString: toString
};

function gatherDataFromResponse(res) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  var body = {
    contents: ""
  };
  res.on("data", (function (buf) {
          body.contents = body.contents + buf.toString();
          
        }));
  res.on("error", (function (error) {
          return Curry._1(resolve, {
                      TAG: /* Error */1,
                      _0: {
                        TAG: /* ServerResponseError */2,
                        _0: error
                      }
                    });
        }));
  res.on("close", (function () {
          return Curry._1(resolve, {
                      TAG: /* Ok */0,
                      _0: body.contents
                    });
        }));
  return match[0];
}

function getWithRedirects(options) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  Https.get(options, (function (res) {
          var statusCode = res.statusCode;
          if (!(statusCode === 302 || statusCode === 301)) {
            return Curry._1(resolve, {
                        TAG: /* Ok */0,
                        _0: res
                      });
          }
          var headers = res.headers;
          var urlAfterRedirect = headers.location;
          if (urlAfterRedirect !== undefined) {
            Https.get(urlAfterRedirect, (function (resAfterRedirect) {
                    return Curry._1(resolve, {
                                TAG: /* Ok */0,
                                _0: resAfterRedirect
                              });
                  }));
            return ;
          } else {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: /* NoRedirectLocation */0
                      });
          }
        }));
  return match[0];
}

var HTTP = {
  gatherDataFromResponse: gatherDataFromResponse,
  getWithRedirects: getWithRedirects
};

var Entry = {};

var ZipFile = {};

var Yauzl$1 = {
  Entry: Entry,
  ZipFile: ZipFile
};

function run(src, dest) {
  var match = $$Promise.pending(undefined);
  var resolve = match[1];
  var fileStream = Fs.createWriteStream(dest, {
        mode: 484
      });
  fileStream.on("error", (function (exn) {
          return Curry._1(resolve, {
                      TAG: /* Error */1,
                      _0: {
                        TAG: /* CannotUnzipFileWithExn */8,
                        _0: exn
                      }
                    });
        }));
  fileStream.on("close", (function () {
          return Curry._1(resolve, {
                      TAG: /* Ok */0,
                      _0: undefined
                    });
        }));
  Yauzl.open(src, (function (err, result) {
          if (err !== null) {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: {
                          TAG: /* CannotUnzipFileWithExn */8,
                          _0: err
                        }
                      });
          }
          if (result === undefined) {
            return Curry._1(resolve, {
                        TAG: /* Error */1,
                        _0: /* CannotUnzipFile */1
                      });
          }
          var zipFile = Caml_option.valFromOption(result);
          zipFile.on("entry", (function (entry) {
                  zipFile.openReadStream(entry, (function (err2, result2) {
                          if (err2 !== null) {
                            return Curry._1(resolve, {
                                        TAG: /* Error */1,
                                        _0: {
                                          TAG: /* CannotUnzipFileWithExn */8,
                                          _0: err2
                                        }
                                      });
                          } else if (result2 !== undefined) {
                            Caml_option.valFromOption(result2).pipe(fileStream);
                            return ;
                          } else {
                            return Curry._1(resolve, {
                                        TAG: /* Error */1,
                                        _0: /* CannotUnzipFile */1
                                      });
                          }
                        }));
                  
                }));
          
        }));
  return match[0];
}

var Unzip = {
  Yauzl: Yauzl$1,
  run: run
};

function decode(json) {
  return {
          name: Json_decode.field("name", Json_decode.string, json),
          url: Json_decode.field("browser_download_url", Json_decode.string, json)
        };
}

var Asset = {
  decode: decode
};

function decode$1(json) {
  return {
          tagName: Json_decode.field("tag_name", Json_decode.string, json),
          assets: Json_decode.field("assets", (function (param) {
                  return Json_decode.array(decode, param);
                }), json)
        };
}

function parseMetadata(json) {
  try {
    return {
            TAG: /* Ok */0,
            _0: Json_decode.array(decode$1, json)
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Json_decode.DecodeError) {
      return {
              TAG: /* Error */1,
              _0: {
                TAG: /* ResponseDecodeError */1,
                _0: e._1,
                _1: json
              }
            };
    }
    throw e;
  }
}

function getReleasesFromGitHub(param) {
  var httpOptions = {
    host: "api.github.com",
    path: "/repos/scmlab/gcl/releases",
    headers: {
      "User-Agent": "gcl-vscode"
    }
  };
  return $$Promise.flatMapOk($$Promise.flatMapOk(getWithRedirects(httpOptions), gatherDataFromResponse), (function (raw) {
                try {
                  return $$Promise.resolved(parseMetadata(JSON.parse(raw)));
                }
                catch (exn){
                  return $$Promise.resolved({
                              TAG: /* Error */1,
                              _0: {
                                TAG: /* ResponseParseError */0,
                                _0: raw
                              }
                            });
                }
              }));
}

var Release = {
  decode: decode$1,
  parseMetadata: parseMetadata,
  getReleasesFromGitHub: getReleasesFromGitHub
};

function getCurrentVersion(globalStoragePath) {
  var getCurrentRelease = function (releases) {
    var matched = Belt_Array.keep(releases, (function (release) {
            return release.tagName === Config$Guabao.version;
          }));
    var release = Belt_Array.get(matched, 0);
    if (release !== undefined) {
      return $$Promise.resolved({
                  TAG: /* Ok */0,
                  _0: release
                });
    } else {
      return $$Promise.resolved({
                  TAG: /* Error */1,
                  _0: {
                    TAG: /* NoMatchingVersion */3,
                    _0: Config$Guabao.version
                  }
                });
    }
  };
  var toDestPath = function (globalStoragePath, release, asset) {
    var osName = asset.name.slice(4, -4);
    return Path.join(globalStoragePath, "gcl-" + release.tagName + "-" + osName);
  };
  var getCurrentAsset = function (release) {
    var os = Process.platform;
    var expectedName;
    switch (os) {
      case "darwin" :
          expectedName = {
            TAG: /* Ok */0,
            _0: "gcl-macos.zip"
          };
          break;
      case "linux" :
          expectedName = {
            TAG: /* Ok */0,
            _0: "gcl-ubuntu.zip"
          };
          break;
      case "win32" :
          expectedName = {
            TAG: /* Ok */0,
            _0: "gcl-windows.zip"
          };
          break;
      default:
        expectedName = {
          TAG: /* Error */1,
          _0: {
            TAG: /* NotSupportedOS */4,
            _0: os
          }
        };
    }
    return $$Promise.resolved(Belt_Result.flatMap(expectedName, (function (name) {
                      var matched = Belt_Array.keep(release.assets, (function (asset) {
                              return asset.name === name;
                            }));
                      var asset = Belt_Array.get(matched, 0);
                      if (asset !== undefined) {
                        return {
                                TAG: /* Ok */0,
                                _0: {
                                  srcUrl: asset.url,
                                  destPath: toDestPath(globalStoragePath, release, asset),
                                  version: release.tagName
                                }
                              };
                      } else {
                        return {
                                TAG: /* Error */1,
                                _0: {
                                  TAG: /* NotSupportedOS */4,
                                  _0: os
                                }
                              };
                      }
                    })));
  };
  return $$Promise.flatMapOk($$Promise.flatMapOk(getReleasesFromGitHub(undefined), getCurrentRelease), getCurrentAsset);
}

var Metadata = {
  Asset: Asset,
  Release: Release,
  getCurrentVersion: getCurrentVersion
};

function download(srcUrl, destPath) {
  var url = Url.parse(srcUrl);
  var httpOptions = {
    host: url.host,
    path: url.path,
    headers: {
      "User-Agent": "gcl-vscode"
    }
  };
  return $$Promise.flatMapOk(getWithRedirects(httpOptions), (function (res) {
                var match = $$Promise.pending(undefined);
                var resolve = match[1];
                var fileStream = Fs.createWriteStream(destPath);
                fileStream.on("error", (function (exn) {
                        return Curry._1(resolve, {
                                    TAG: /* Error */1,
                                    _0: {
                                      TAG: /* CannotWriteFile */7,
                                      _0: exn
                                    }
                                  });
                      }));
                fileStream.on("close", (function () {
                        return Curry._1(resolve, {
                                    TAG: /* Ok */0,
                                    _0: undefined
                                  });
                      }));
                res.pipe(fileStream);
                return match[0];
              }));
}

function downloadLanguageServer(metadata) {
  return $$Promise.flatMap($$Promise.flatMapOk($$Promise.flatMapOk($$Promise.flatMapOk(download(metadata.srcUrl, metadata.destPath + ".zip.download"), (function (param) {
                            return $$Promise.mapError(rename(metadata.destPath + ".zip.download", metadata.destPath + ".zip"), (function (e) {
                                          return {
                                                  TAG: /* CannotRenameFile */6,
                                                  _0: e
                                                };
                                        }));
                          })), (function (param) {
                        return run(metadata.destPath + ".zip", metadata.destPath);
                      })), (function (param) {
                    return $$Promise.mapError(unlink(metadata.destPath + ".zip"), (function (e) {
                                  return {
                                          TAG: /* CannotDeleteFile */5,
                                          _0: e
                                        };
                                }));
                  })), (function (result) {
                if (result.TAG === /* Ok */0) {
                  return $$Promise.resolved({
                              TAG: /* Ok */0,
                              _0: metadata.destPath
                            });
                }
                var error = result._0;
                var remove = function (path) {
                  if (Fs.existsSync(path)) {
                    return $$Promise.map(unlink(path), (function (param) {
                                  
                                }));
                  } else {
                    return $$Promise.resolved(undefined);
                  }
                };
                return $$Promise.map($$Promise.allArray([
                                remove(metadata.destPath + ".zip.download"),
                                remove(metadata.destPath + ".zip")
                              ]), (function (param) {
                              return {
                                      TAG: /* Error */1,
                                      _0: error
                                    };
                            }));
              }));
}

function checkExistingDownload(globalStoragePath) {
  if (!Fs.existsSync(globalStoragePath)) {
    Fs.mkdirSync(globalStoragePath);
  }
  var others = Process.platform;
  var getExpectedFileName;
  switch (others) {
    case "darwin" :
        getExpectedFileName = {
          TAG: /* Ok */0,
          _0: "gcl-" + Config$Guabao.version + "-macos"
        };
        break;
    case "linux" :
        getExpectedFileName = {
          TAG: /* Ok */0,
          _0: "gcl-" + Config$Guabao.version + "-ubuntu"
        };
        break;
    case "win32" :
        getExpectedFileName = {
          TAG: /* Ok */0,
          _0: "gcl-" + Config$Guabao.version + "-windows"
        };
        break;
    default:
      getExpectedFileName = {
        TAG: /* Error */1,
        _0: {
          TAG: /* NotSupportedOS */4,
          _0: others
        }
      };
  }
  return Belt_Result.map(getExpectedFileName, (function (expected) {
                var fileNames = Fs.readdirSync(globalStoragePath);
                var downloaded = fileNames.some(function (actual) {
                      return expected === actual;
                    });
                if (downloaded) {
                  return Path.join(globalStoragePath, expected);
                }
                
              }));
}

var state = {
  contents: undefined
};

function get(globalStoragePath) {
  var match = state.contents;
  if (match !== undefined) {
    if (match.TAG === /* Downloaded */0) {
      return $$Promise.resolved({
                  TAG: /* Ok */0,
                  _0: match._0
                });
    } else {
      return match._0;
    }
  }
  var error = checkExistingDownload(globalStoragePath);
  if (error.TAG !== /* Ok */0) {
    return $$Promise.resolved({
                TAG: /* Error */1,
                _0: error._0
              });
  }
  var path = error._0;
  if (path !== undefined) {
    state.contents = {
      TAG: /* Downloaded */0,
      _0: path
    };
    return $$Promise.resolved({
                TAG: /* Ok */0,
                _0: path
              });
  }
  var match$1 = $$Promise.pending(undefined);
  state.contents = {
    TAG: /* InFlight */1,
    _0: match$1[0]
  };
  return $$Promise.tap($$Promise.flatMapOk(getCurrentVersion(globalStoragePath), downloadLanguageServer), match$1[1]);
}

var Module = {
  get: get
};

exports.Nd = Nd;
exports.$$Error = $$Error;
exports.HTTP = HTTP;
exports.Unzip = Unzip;
exports.Metadata = Metadata;
exports.Module = Module;
exports.get = get;
/* fs Not a pure module */
