// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/lib/js/src/Json.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Process$AgdaModeVscode = require("agda-mode-vscode/lib/js/src/Process.bs.js");
var Connection__Prebuilt$Guabao = require("./Connection__Prebuilt.bs.js");

function toString(error) {
  switch (error.TAG | 0) {
    case /* CannotConnectViaStdIO */0 :
        var match = Curry._1(Process$AgdaModeVscode.PathSearch.$$Error.toString, error._0);
        return [
                "Cannot locate \"gcl\"",
                match[1] + "\nPlease make sure that the executable is in the path"
              ];
    case /* CannotConnectViaTCP */1 :
        return [
                "Cannot connect with the server",
                "Please enter \":main -d\" in ghci"
              ];
    case /* CannotConnectViaPrebuilt */2 :
        return [
                "Cannot download prebuilt language server",
                Connection__Prebuilt$Guabao.$$Error.toString(error._0)
              ];
    case /* ConnectionError */3 :
        var exn = error._0;
        var isECONNREFUSED = Belt_Option.mapWithDefault(exn.message, false, (function (param) {
                return param.startsWith("connect ECONNREFUSED");
              }));
        if (isECONNREFUSED) {
          return [
                  "LSP Connection Error",
                  "Please enter \":main -d\" in ghci"
                ];
        } else {
          return [
                  "LSP Client Error",
                  Belt_Option.getWithDefault(exn.message, "")
                ];
        }
    case /* CannotSendRequest */4 :
        return [
                "PANIC: Cannot send request",
                "Please file an issue\n" + Belt_Option.getWithDefault(error._0.message, "")
              ];
    case /* CannotDecodeResponse */5 :
        return [
                "PANIC: Cannot decode response",
                "Please file an issue\n\n" + error._0 + "\n" + Json.stringify(error._1)
              ];
    
  }
}

exports.toString = toString;
/* Process-AgdaModeVscode Not a pure module */
