// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/lib/js/src/Json.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Source__Path$LanguageServerMule = require("language-server-mule/lib/js/src/Source/Source__Path.bs.js");
var Source__Prebuilt$LanguageServerMule = require("language-server-mule/lib/js/src/Source/Source__Prebuilt.bs.js");

function toString(error) {
  switch (error.TAG | 0) {
    case /* CannotConnectViaStdIO */0 :
        var body = Source__Path$LanguageServerMule.$$Error.toString(error._0);
        return [
                "Cannot locate \"gcl\"",
                body + "\nPlease make sure that the executable is in the path"
              ];
    case /* CannotConnectViaTCP */1 :
        return [
                "Cannot connect with the server via TCP",
                "Please enter \":main -d\" in ghci"
              ];
    case /* CannotConnectViaPrebuilt */2 :
        return [
                "Cannot download prebuilt language server",
                Source__Prebuilt$LanguageServerMule.$$Error.toString(error._0)
              ];
    case /* ConnectionError */3 :
        var exn = error._0;
        var isECONNREFUSED = Belt_Option.mapWithDefault(exn.message, false, (function (param) {
                return param.startsWith("connect ECONNREFUSED");
              }));
        if (isECONNREFUSED) {
          return [
                  "LSP Connection Error",
                  "Please enter \":main -d\" in ghci"
                ];
        } else {
          return [
                  "LSP Client Error",
                  Belt_Option.getWithDefault(exn.message, "")
                ];
        }
    case /* CannotSendRequest */4 :
        return [
                "PANIC: Cannot send request",
                "Please file an issue\n" + Belt_Option.getWithDefault(error._0.message, "")
              ];
    case /* CannotDecodeResponse */5 :
        return [
                "PANIC: Cannot decode response",
                "Please file an issue\n\n" + error._0 + "\n" + Json.stringify(error._1)
              ];
    
  }
}

exports.toString = toString;
/* Source__Path-LanguageServerMule Not a pure module */
