// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var Util$Guabao = require("../../../Util/Util.bs.js");
var SrcLoc$Guabao = require("../../../SrcLoc.bs.js");

function decode(param) {
  return Json_decode.array(Json_decode.string, param);
}

function encode(param) {
  return Json_encode.array((function (prim) {
                return prim;
              }), param);
}

var ClassNames = {
  decode: decode,
  encode: encode
};

function decode$1(param) {
  return /* Assigment */0;
}

function encode$1(param) {
  return "RRAssigment";
}

var RewriteReason = {
  decode: decode$1,
  encode: encode$1
};

function decode$2(param) {
  return Util$Guabao.Decode.sum(function (x) {
              switch (x) {
                case "Horz" :
                    var partial_arg = decode$2(undefined);
                    var partial_arg$1 = function (param) {
                      return Json_decode.array(partial_arg, param);
                    };
                    var partial_arg$2 = function (param) {
                      return Json_decode.array(partial_arg$1, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (xs) {
                                              return {
                                                      TAG: /* Horz */5,
                                                      _0: xs
                                                    };
                                            }), partial_arg$2, param);
                              })
                          };
                case "Icon" :
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (param) {
                                              return {
                                                      TAG: /* Icon */0,
                                                      _0: param[0],
                                                      _1: param[1]
                                                    };
                                            }), (function (param) {
                                              return Json_decode.pair(Json_decode.string, decode, param);
                                            }), param);
                              })
                          };
                case "Link" :
                    var partial_arg$3 = decode$2(undefined);
                    var partial_arg$4 = function (param) {
                      return Json_decode.array(partial_arg$3, param);
                    };
                    var partial_arg$5 = function (param) {
                      return Json_decode.tuple3(SrcLoc$Guabao.$$Range.decode, partial_arg$4, decode, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (param) {
                                              return {
                                                      TAG: /* Link */2,
                                                      _0: param[0],
                                                      _1: param[1],
                                                      _2: param[2]
                                                    };
                                            }), partial_arg$5, param);
                              })
                          };
                case "Parn" :
                    var partial_arg$6 = decode$2(undefined);
                    var partial_arg$7 = function (param) {
                      return Json_decode.array(partial_arg$6, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (x) {
                                              return {
                                                      TAG: /* Parn */7,
                                                      _0: x
                                                    };
                                            }), partial_arg$7, param);
                              })
                          };
                case "PrHz" :
                    var partial_arg$8 = decode$2(undefined);
                    var partial_arg$9 = function (param) {
                      return Json_decode.array(partial_arg$8, param);
                    };
                    var partial_arg$10 = function (param) {
                      return Json_decode.array(partial_arg$9, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (xs) {
                                              return {
                                                      TAG: /* PrHz */8,
                                                      _0: xs
                                                    };
                                            }), partial_arg$10, param);
                              })
                          };
                case "Sbst" :
                    var partial_arg$11 = decode$2(undefined);
                    var partial_arg$12 = function (param) {
                      return Json_decode.array(partial_arg$11, param);
                    };
                    var partial_arg$13 = decode$2(undefined);
                    var partial_arg$14 = function (param) {
                      return Json_decode.array(partial_arg$13, param);
                    };
                    var partial_arg$15 = decode$2(undefined);
                    var partial_arg$16 = function (param) {
                      return Json_decode.array(partial_arg$15, param);
                    };
                    var partial_arg$17 = function (param) {
                      return Json_decode.tuple4(partial_arg$16, partial_arg$14, partial_arg$12, decode, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (param) {
                                              return {
                                                      TAG: /* Sbst */3,
                                                      _0: param[0],
                                                      _1: param[1],
                                                      _2: param[2],
                                                      _3: param[3]
                                                    };
                                            }), partial_arg$17, param);
                              })
                          };
                case "Sbst2" :
                    var partial_arg$18 = decode$2(undefined);
                    var partial_arg$19 = function (param) {
                      return Json_decode.array(partial_arg$18, param);
                    };
                    var partial_arg$20 = decode$2(undefined);
                    var partial_arg$21 = function (param) {
                      return Json_decode.array(partial_arg$20, param);
                    };
                    var partial_arg$22 = decode$2(undefined);
                    var partial_arg$23 = function (param) {
                      return Json_decode.array(partial_arg$22, param);
                    };
                    var partial_arg$24 = function (param) {
                      return Util$Guabao.Decode.tuple5(decode$1, partial_arg$23, partial_arg$21, partial_arg$19, decode, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (param) {
                                              return {
                                                      TAG: /* Sbst2 */4,
                                                      _0: param[0],
                                                      _1: param[1],
                                                      _2: param[2],
                                                      _3: param[3],
                                                      _4: param[4]
                                                    };
                                            }), partial_arg$24, param);
                              })
                          };
                case "Text" :
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (param) {
                                              return {
                                                      TAG: /* Text */1,
                                                      _0: param[0],
                                                      _1: param[1]
                                                    };
                                            }), (function (param) {
                                              return Json_decode.pair(Json_decode.string, decode, param);
                                            }), param);
                              })
                          };
                case "Vert" :
                    var partial_arg$25 = decode$2(undefined);
                    var partial_arg$26 = function (param) {
                      return Json_decode.array(partial_arg$25, param);
                    };
                    var partial_arg$27 = function (param) {
                      return Json_decode.array(partial_arg$26, param);
                    };
                    return {
                            TAG: /* Contents */0,
                            _0: (function (param) {
                                return Json_decode.map((function (xs) {
                                              return {
                                                      TAG: /* Vert */6,
                                                      _0: xs
                                                    };
                                            }), partial_arg$27, param);
                              })
                          };
                default:
                  throw {
                        RE_EXN_ID: Json_decode.DecodeError,
                        _1: "[Element.Inline] Unknown constructor: " + x,
                        Error: new Error()
                      };
              }
            });
}

var decode$3 = decode$2(undefined);

function encode$2(x) {
  switch (x.TAG | 0) {
    case /* Icon */0 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Icon"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.pair((function (prim) {
                                return prim;
                              }), encode, [
                              x._0,
                              x._1
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Text */1 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Text"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.pair((function (prim) {
                                return prim;
                              }), encode, [
                              x._0,
                              x._1
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Link */2 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Link"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple3(SrcLoc$Guabao.$$Range.encode, (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), encode, [
                              x._0,
                              x._1,
                              x._2
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Sbst */3 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Sbst"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple4((function (param) {
                                return Json_encode.array(encode$2, param);
                              }), (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), encode, [
                              x._0,
                              x._1,
                              x._2,
                              x._3
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Sbst2 */4 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Sbst2"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Util$Guabao.Encode.tuple5(encode$1, (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), (function (param) {
                                return Json_encode.array(encode$2, param);
                              }), encode, [
                              x._0,
                              x._1,
                              x._2,
                              x._3,
                              x._4
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Horz */5 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Horz"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.array((function (param) {
                                return Json_encode.array(encode$2, param);
                              }), x._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Vert */6 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Vert"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.array((function (param) {
                                return Json_encode.array(encode$2, param);
                              }), x._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Parn */7 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "Parn"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.array(encode$2, x._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* PrHz */8 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "PrHz"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.array((function (param) {
                                return Json_encode.array(encode$2, param);
                              }), x._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    
  }
}

var Inline = {
  decode: decode$3,
  encode: encode$2
};

function string(s) {
  return /* Element */{
          _0: [{
              TAG: /* Text */1,
              _0: s,
              _1: []
            }]
        };
}

function decode$4(param) {
  return Json_decode.map((function (elems) {
                return /* Element */{
                        _0: elems
                      };
              }), (function (param) {
                return Json_decode.array(decode$3, param);
              }), param);
}

function encode$3(x) {
  return Json_encode.array(encode$2, x._0);
}

exports.ClassNames = ClassNames;
exports.RewriteReason = RewriteReason;
exports.Inline = Inline;
exports.string = string;
exports.decode = decode$4;
exports.encode = encode$3;
/* decode Not a pure module */
