// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Common$Space(Props) {
  return React.createElement("div", {
              className: "expr-space"
            }, " ");
}

var Space = {
  make: Common$Space
};

function Common$Paren(Props) {
  var activate = Props.activate;
  var children = Props.children;
  var match = React.useState(function () {
        return false;
      });
  var setHover = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setCollapse = match$1[1];
  var collapsed = match$1[0];
  var onMouseOver = function (param) {
    return Curry._1(setHover, (function (param) {
                  return true;
                }));
  };
  var onMouseLeave = function (param) {
    return Curry._1(setHover, (function (param) {
                  return false;
                }));
  };
  var onClick = function (param) {
    return Curry._1(setCollapse, (function (param) {
                  if (collapsed) {
                    return false;
                  } else {
                    return true;
                  }
                }));
  };
  var className = "expr-paren" + ((
      match[0] ? " hovered" : ""
    ) + (
      collapsed ? " collapsed" : ""
    ));
  if (activate) {
    if (collapsed) {
      return React.createElement("div", {
                  className: className,
                  onClick: onClick,
                  onMouseLeave: onMouseLeave,
                  onMouseOver: onMouseOver
                }, "(...)");
    } else {
      return React.createElement(React.Fragment, undefined, React.createElement("div", {
                      className: className,
                      onClick: onClick,
                      onMouseLeave: onMouseLeave,
                      onMouseOver: onMouseOver
                    }, "("), children, React.createElement("div", {
                      className: className,
                      onClick: onClick,
                      onMouseLeave: onMouseLeave,
                      onMouseOver: onMouseOver
                    }, ")"));
    }
  } else {
    return children;
  }
}

var Paren = {
  make: Common$Paren
};

exports.Space = Space;
exports.Paren = Paren;
/* react Not a pure module */
