// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function DevPanel(Props) {
  var devMode = Props.devMode;
  var status = Props.status;
  var onConnect = Props.onConnect;
  var onDisconnect = Props.onDisconnect;
  var onConnect$1 = function (param) {
    return Curry._1(onConnect, undefined);
  };
  var onDisconnect$1 = function (param) {
    return Curry._1(onDisconnect, undefined);
  };
  var status$1;
  switch (status) {
    case /* Disconnected */0 :
        status$1 = React.createElement("div", {
              className: "disconnected",
              id: "gcl-dev-panel-status",
              onClick: onConnect$1
            }, React.createElement("i", {
                  className: "codicon codicon-circle-large-filled"
                }), React.createElement("span", undefined, "disconnected"));
        break;
    case /* Connecting */1 :
        status$1 = React.createElement("div", {
              className: "connecting",
              id: "gcl-dev-panel-status"
            }, React.createElement("i", {
                  className: "codicon codicon-circle-large-filled"
                }), React.createElement("span", undefined, "connecting"));
        break;
    case /* Connected */2 :
        status$1 = React.createElement("div", {
              className: "connected",
              id: "gcl-dev-panel-status",
              onClick: onDisconnect$1
            }, React.createElement("i", {
                  className: "codicon codicon-circle-large-filled"
                }), React.createElement("span", undefined, "connected"));
        break;
    
  }
  var className = "gcl-dev-panel " + (
    devMode ? "" : "hidden"
  );
  return React.createElement("div", {
              className: className
            }, React.createElement("div", {
                  id: "gcl-dev-panel-header"
                }, "dev mode"), status$1);
}

var make = DevPanel;

exports.make = make;
/* react Not a pure module */
