// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function DevPanel(Props) {
  var devMode = Props.devMode;
  var method = Props.method;
  var status = Belt_Option.isSome(method) ? React.createElement("div", {
          className: "connected",
          id: "gcl-dev-panel-status"
        }, React.createElement("i", {
              className: "codicon codicon-circle-large-filled"
            }), React.createElement("span", undefined, "connected")) : React.createElement("div", {
          className: "disconnected",
          id: "gcl-dev-panel-status"
        }, React.createElement("i", {
              className: "codicon codicon-circle-large-filled"
            }), React.createElement("span", undefined, "disconnected"));
  var method$1 = method !== undefined ? (
      method.TAG === /* ViaStdIO */0 ? React.createElement("div", {
              id: "gcl-dev-panel-method"
            }, React.createElement("i", {
                  className: "codicon codicon-plug"
                }), React.createElement("span", undefined, "via StdIO")) : React.createElement("div", {
              id: "gcl-dev-panel-method"
            }, React.createElement("i", {
                  className: "codicon codicon-plug"
                }), React.createElement("span", undefined, "via TCP"))
    ) : React.createElement(React.Fragment, undefined);
  var className = "gcl-dev-panel " + (
    devMode ? "" : "hidden"
  );
  return React.createElement("div", {
              className: className
            }, React.createElement("div", {
                  id: "gcl-dev-panel-header"
                }, "dev mode"), method$1, status);
}

var make = DevPanel;

exports.make = make;
/* react Not a pure module */
