// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Body$Guacamole = require("./Body.bs.js");
var Vscode$Guacamole = require("../Vscode.bs.js");

var vscode = acquireVsCodeApi();

function Panel(Props) {
  React.useState((function () {
          return "";
        }));
  var match = React.useState((function () {
          return /* Nothing */0;
        }));
  var setBody = match[1];
  React.useEffect((function () {
          Vscode$Guacamole.Api.onMessage((function (param) {
                  if (typeof param === "number") {
                    return /* () */0;
                  } else {
                    var body = param[1];
                    return Curry._1(setBody, (function (param) {
                                  return body;
                                }));
                  }
                }));
          return ;
        }), []);
  return React.createElement("section", {
              className: "gcl native-key-bindings",
              tabIndex: -1
            }, React.createElement("div", {
                  className: "gcl-header"
                }, "header"), React.createElement(Body$Guacamole.make, {
                  body: match[0]
                }));
}

var make = Panel;

exports.vscode = vscode;
exports.make = make;
/* vscode Not a pure module */
