// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Body$Guacamole = require("./Body.bs.js");
var View$Guacamole = require("../View.bs.js");
var Header$Guacamole = require("./Header.bs.js");
var Vscode$Guacamole = require("../Vscode.bs.js");

var vscode = acquireVsCodeApi();

function Panel(Props) {
  var match = React.useState((function () {
          return /* Loading */0;
        }));
  var setHeader = match[1];
  var match$1 = React.useState((function () {
          return /* Nothing */0;
        }));
  var setBody = match$1[1];
  var match$2 = React.useState((function () {
          return /* WP1 */0;
        }));
  var setMode = match$2[1];
  var onChangeMode = function (mode) {
    return Curry._1(setMode, (function (param) {
                  return mode;
                }));
  };
  React.useEffect((function () {
          Vscode$Guacamole.Api.onMessage((function (stringified) {
                  var param = Curry._1(View$Guacamole.$$Request.decode, JSON.parse(stringified));
                  if (typeof param === "number") {
                    return /* () */0;
                  } else {
                    var body = param[1];
                    var header = param[0];
                    Curry._1(setHeader, (function (param) {
                            return header;
                          }));
                    return Curry._1(setBody, (function (param) {
                                  return body;
                                }));
                  }
                }));
          return ;
        }), []);
  return React.createElement("section", {
              className: "gcl-panel native-key-bindings",
              tabIndex: -1
            }, React.createElement(Header$Guacamole.make, {
                  header: match[0],
                  mode: match$2[0],
                  onChangeMode: onChangeMode
                }), React.createElement(Body$Guacamole.make, {
                  body: match$1[0]
                }));
}

var make = Panel;

exports.vscode = vscode;
exports.make = make;
/* vscode Not a pure module */
