// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Status(Props) {
  var status = Props.status;
  return React.createElement("div", {
              id: "gcl-connection-status"
            }, React.createElement("div", {
                  id: "gcl-connection-status-buttons"
                }, React.createElement("button", {
                      id: "gcl-connection-status-buttons-solve"
                    }, React.createElement("span", {
                          className: "codicon codicon-wand"
                        }), React.createElement("span", {
                          id: "gcl-connection-status-buttons-solve-label"
                        }, "solve"))), React.createElement("div", {
                  id: "gcl-connection-status-version"
                }, status));
}

var make = Status;

exports.make = make;
/* react Not a pure module */
