// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Status(Props) {
  var status = Props.status;
  return React.createElement("div", {
              id: "gcl-connection-status"
            }, status);
}

var make = Status;

exports.make = make;
/* react Not a pure module */
