// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function Status(Props) {
  var status = Props.status;
  var onSolve = Props.onSolve;
  var onClick = function (param) {
    return Curry._1(onSolve, undefined);
  };
  return React.createElement("div", {
              id: "gcl-connection-status"
            }, React.createElement("div", {
                  id: "gcl-connection-status-buttons"
                }, React.createElement("button", {
                      id: "gcl-connection-status-buttons-solve",
                      onClick: onClick
                    }, React.createElement("span", {
                          className: "codicon codicon-wand"
                        }), React.createElement("span", {
                          id: "gcl-connection-status-buttons-solve-label"
                        }, "solve"))), React.createElement("div", {
                  id: "gcl-connection-status-version"
                }, status));
}

var make = Status;

exports.make = make;
/* react Not a pure module */
