// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Util$Guacamole = require("../Util/Util.bs.js");
var Event$Guacamole = require("../Util/Event.bs.js");
var Common$Guacamole = require("./Common.bs.js");

var emitter = Event$Guacamole.make(/* () */0);

var eventContext = React.createContext(emitter);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = eventContext.Provider;

var Provider = {
  makeProps: makeProps,
  make: make
};

function Subst(Props) {
  var expr = Props.expr;
  var subst = Props.subst;
  var makeExpr = Props.makeExpr;
  var makeExprProps = Props.makeExprProps;
  var emitter = React.useContext(eventContext);
  var match = React.useState((function () {
          return false;
        }));
  var setHover = match[1];
  var match$1 = React.useState((function () {
          return false;
        }));
  var setReduced = match$1[1];
  var onMouseOver = function (param) {
    return Curry._1(setHover, (function (param) {
                  return true;
                }));
  };
  var onMouseLeave = function (param) {
    return Curry._1(setHover, (function (param) {
                  return false;
                }));
  };
  var onClick = function (param) {
    Curry._1(setReduced, (function (param) {
            return true;
          }));
    return Curry._1(emitter.emit, /* tuple */[
                expr,
                subst
              ]);
  };
  var className = "expr-subst" + ((
      match[0] ? " hovered" : ""
    ) + (
      match$1[0] ? " reduced" : ""
    ));
  var e = Belt_Array.map(Js_dict.entries(subst), (function (param) {
          return React.createElement(React.Fragment, undefined, React.createElement(makeExpr, Curry._3(makeExprProps, 0, param[1], /* () */0)), "/" + param[0]);
        }));
  return React.createElement(React.Fragment, undefined, React.createElement(makeExpr, Curry._3(makeExprProps, 0, expr, /* () */0)), React.createElement(Common$Guacamole.Space.make, { }), React.createElement("div", {
                  className: className,
                  onClick: onClick,
                  onMouseLeave: onMouseLeave,
                  onMouseOver: onMouseOver
                }, "[", Util$Guacamole.React.sepBy(", ", e), "]"));
}

var make$1 = Subst;

exports.emitter = emitter;
exports.eventContext = eventContext;
exports.Provider = Provider;
exports.make = make$1;
/* emitter Not a pure module */
