// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var GCL$Guacamole = require("../GCL.bs.js");
var Chan$Guacamole = require("../Util/Chan.bs.js");
var Link$Guacamole = require("./Link.bs.js");
var Util$Guacamole = require("../Util/Util.bs.js");
var ReqID$Guacamole = require("./ReqID.bs.js");
var Common$Guacamole = require("./Common.bs.js");

var emitter = Chan$Guacamole.make(undefined);

var eventContext = React.createContext(emitter);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = eventContext.Provider;

var Provider = {
  makeProps: makeProps,
  make: make
};

var counter = {
  contents: 0
};

function Subst(Props) {
  var expr = Props.expr;
  var makePrec = Props.makePrec;
  var makePrecProps = Props.makePrecProps;
  var subst = {};
  var channel = React.useContext(eventContext);
  var match = React.useState(function () {
        return {
                TAG: 0,
                _0: expr,
                [Symbol.for("name")]: "Unreduced"
              };
      });
  var setRedux = match[1];
  var redux = match[0];
  var id = React.useRef(undefined);
  var reqID = React.useRef(undefined);
  var match$1 = React.useState(function () {
        return false;
      });
  var setHover = match$1[1];
  var onMouseOver = function (param) {
    return Curry._1(setHover, (function (param) {
                  return true;
                }));
  };
  var onMouseLeave = function (param) {
    return Curry._1(setHover, (function (param) {
                  return false;
                }));
  };
  var onClick = function (param) {
    Chan$Guacamole.emit(channel, {
          TAG: 0,
          _0: counter.contents,
          _1: expr,
          _2: subst,
          [Symbol.for("name")]: "Request"
        });
    id.current = counter.contents;
    counter.contents = counter.contents + 1 | 0;
    
  };
  var tmp;
  tmp = typeof redux === "number" || !redux.TAG ? "" : " reduced";
  var className = "expr-subst" + ((
      match$1[0] ? " hovered" : ""
    ) + tmp);
  reqID.current = React.useContext(ReqID$Guacamole.context);
  if (typeof redux !== "number" && redux.TAG) {
    if (Caml_obj.caml_notequal(redux._0, reqID.current)) {
      Curry._1(setRedux, (function (param) {
              return {
                      TAG: 0,
                      _0: expr,
                      [Symbol.for("name")]: "Unreduced"
                    };
            }));
    }
    
  }
  React.useEffect((function () {
          return Chan$Guacamole.on(channel, (function (param) {
                        if (!param.TAG) {
                          return ;
                        }
                        if (!Caml_obj.caml_equal(param._0, id.current)) {
                          return ;
                        }
                        var expr = param._1;
                        return Curry._1(setRedux, (function (param) {
                                      return {
                                              TAG: 1,
                                              _0: reqID.current,
                                              _1: expr,
                                              [Symbol.for("name")]: "Reduced"
                                            };
                                    }));
                      }));
        }), []);
  if (typeof redux === "number") {
    return React.createElement(React.Fragment, undefined, "...");
  }
  if (redux.TAG) {
    return React.createElement(Common$Guacamole.Paren.make, {
                activate: true,
                children: React.createElement(makePrec, Curry._3(makePrecProps, 0, redux._1, undefined))
              });
  }
  var expr$1 = redux._0;
  switch (expr$1.TAG | 0) {
    case /* Const */2 :
        return React.createElement(Link$Guacamole.make, {
                    loc: expr$1._1,
                    children: React.createElement("div", {
                          className: className,
                          onClick: onClick,
                          onMouseLeave: onMouseLeave,
                          onMouseOver: onMouseOver
                        }, Curry._1(GCL$Guacamole.Syntax.Name.toString, expr$1._0))
                  });
    case /* Subst */8 :
        var subst$1 = expr$1._1;
        var expressions = Belt_Array.map(Js_dict.values(subst$1), (function (value) {
                return React.createElement(makePrec, Curry._3(makePrecProps, 0, value, undefined));
              }));
        var variables = Belt_Array.map(Object.keys(subst$1), (function (value) {
                return React.createElement(React.Fragment, undefined, value);
              }));
        return React.createElement(Link$Guacamole.make, {
                    loc: /* NoLoc */0,
                    children: null
                  }, React.createElement(makePrec, Curry._3(makePrecProps, 0, expr$1._0, undefined)), React.createElement(Common$Guacamole.Space.make, {}), React.createElement("div", {
                        className: className,
                        onClick: onClick,
                        onMouseLeave: onMouseLeave,
                        onMouseOver: onMouseOver
                      }, "[", Util$Guacamole.React.sepBy(", ", expressions), "/", Util$Guacamole.React.sepBy(", ", variables), "]"));
    default:
      return React.createElement(React.Fragment, undefined);
  }
}

var make$1 = Subst;

exports.emitter = emitter;
exports.eventContext = eventContext;
exports.Provider = Provider;
exports.counter = counter;
exports.make = make$1;
/* emitter Not a pure module */
