// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var VSCode = require("bs-vscode/lib/js/src/VSCode.bs.js");
var ReactDom = require("react-dom");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Chan$Guabao = require("../Util/Chan.bs.js");
var Panel$Guabao = require("./Panel.bs.js");
var ViewType$Guabao = require("./ViewType.bs.js");

var vscode = acquireVsCodeApi();

var onRequest = Chan$Guabao.make(undefined);

VSCode.Api.onMessage(function (stringifiedJSON) {
      var request = Curry._1(ViewType$Guabao.$$Request.decode, JSON.parse(stringifiedJSON));
      return Chan$Guabao.emit(onRequest, request);
    });

var onResponse = Chan$Guabao.make(undefined);

Chan$Guabao.on(onResponse, (function (response) {
        vscode.postMessage(ViewType$Guabao.$$Response.encode(response));
        
      }));

Belt_Option.forEach(Caml_option.nullable_to_opt(document.getElementById("root")), (function (element) {
        ReactDom.render(React.createElement(Panel$Guabao.make, {
                  onRequest: onRequest,
                  onResponse: onResponse
                }), element);
        
      }));

exports.vscode = vscode;
exports.onRequest = onRequest;
exports.onResponse = onResponse;
/* vscode Not a pure module */
