// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Eventemitter3 = require("eventemitter3");

function on(prim, prim$1, prim$2) {
  return prim$2.addListener(prim, prim$1);
}

function on2(prim, prim$1, prim$2) {
  return prim$2.addListener(prim, prim$1);
}

function on3(prim, prim$1, prim$2) {
  return prim$2.addListener(prim, prim$1);
}

function removeListener(prim, prim$1, prim$2) {
  return prim$2.off(prim, prim$1);
}

function removeListener2(prim, prim$1, prim$2) {
  return prim$2.off(prim, prim$1);
}

function removeListener3(prim, prim$1, prim$2) {
  return prim$2.off(prim, prim$1);
}

var EventEmitter3 = {
  on: on,
  on2: on2,
  on3: on3,
  removeListener: removeListener,
  removeListener2: removeListener2,
  removeListener3: removeListener3
};

function make(param) {
  var emitter = new Eventemitter3.EventEmitter();
  return {
          emitter: emitter,
          emit: (function (x) {
              emitter.emit("data", x);
              
            }),
          once: (function (param) {
              var match = $$Promise.pending(undefined);
              emitter.once("data", match[1]);
              return match[0];
            }),
          on: (function (callback) {
              emitter.addListener("data", callback);
              return function (param) {
                emitter.off("data", callback);
                
              };
            }),
          destroy: (function (param) {
              emitter.removeAllListeners();
              
            })
        };
}

exports.EventEmitter3 = EventEmitter3;
exports.make = make;
/* Promise Not a pure module */
