// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Chan$Guacamole = require("./Chan.bs.js");

function make(param) {
  return {
          req: Chan$Guacamole.make(undefined),
          res: Chan$Guacamole.make(undefined)
        };
}

function send(self, req) {
  var promise = Chan$Guacamole.once(self.res);
  Chan$Guacamole.emit(self.req, req);
  return promise;
}

function recv(self, handler) {
  return Chan$Guacamole.on(self.req, (function (res) {
                var partial_arg = self.res;
                return $$Promise.get(Curry._1(handler, res), (function (param) {
                              return Chan$Guacamole.emit(partial_arg, param);
                            }));
              }));
}

function destroy(self) {
  Chan$Guacamole.destroy(self.req);
  return Chan$Guacamole.destroy(self.res);
}

var Module = {
  make: make,
  send: send,
  recv: recv,
  destroy: destroy
};

exports.Module = Module;
exports.make = make;
exports.send = send;
exports.recv = recv;
exports.destroy = destroy;
/* Promise Not a pure module */
