// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");

function getFileName(editor) {
  return editor.document.fileName;
}

function setGCLPath(path) {
  return Vscode.workspace.getConfiguration("guacamole", undefined).update("gclPath", path, 1, undefined);
}

function getGCLPath(param) {
  return Vscode.workspace.getConfiguration("guacamole", undefined).get("gclPath");
}

var Impl = {
  getFileName: getFileName,
  getGCLPath: getGCLPath,
  setGCLPath: setGCLPath
};

exports.Impl = Impl;
exports.getFileName = getFileName;
exports.getGCLPath = getGCLPath;
exports.setGCLPath = setGCLPath;
/* vscode Not a pure module */
