// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_list = require("bs-platform/lib/js/js_list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");
var Task__Error$Guacamole = require("./Task__Error.bs.js");
var Task__Types$Guacamole = require("./Task__Types.bs.js");

function Impl(Editor, State) {
  var partial_arg = Task__Types$Guacamole.Impl;
  var Task__Types = (function (param) {
        return partial_arg(Editor, param);
      })(State);
  var partial_arg$1 = Task__Error$Guacamole.Impl;
  var Task__Error = (function (param) {
        return partial_arg$1(Editor, param);
      })(State);
  var State$1 = Curry._1(State, Editor);
  var handle = function (response) {
    switch (response.tag | 0) {
      case /* Error */0 :
          return Js_list.flatten(Belt_List.fromArray(Belt_Array.map(response[0], Task__Error.handle)));
      case /* OK */1 :
          var specifications = response[1];
          return /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* SetSpecifications */Caml_chrome_debugger.variant("SetSpecifications", 1, [specifications]),
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        /* AddDecorations */Caml_chrome_debugger.variant("AddDecorations", 2, [specifications]),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            /* Display */Caml_chrome_debugger.variant("Display", 5, [
                                /* Plain */Caml_chrome_debugger.variant("Plain", 0, ["Proof Obligations"]),
                                /* ProofObligations */Caml_chrome_debugger.variant("ProofObligations", 0, [response[0]])
                              ]),
                            /* [] */0
                          ])
                      ])
                  ]);
      case /* Resolve */2 :
      case /* InsertAssertion */3 :
          return /* [] */0;
      case /* UnknownResponse */4 :
          return /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* Display */Caml_chrome_debugger.variant("Display", 5, [
                        /* Error */Caml_chrome_debugger.variant("Error", 1, ["Panic: unknown response from GCL"]),
                        /* Plain */Caml_chrome_debugger.variant("Plain", 1, [JSON.stringify(response[0])])
                      ]),
                    /* [] */0
                  ]);
      
    }
  };
  return {
          Task__Types: Task__Types,
          Task__Error: Task__Error,
          State: State$1,
          handle: handle
        };
}

exports.Impl = Impl;
/* Task__Error-Guacamole Not a pure module */
