// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var names = [
  [
    /* Reload */2,
    "reload"
  ],
  [
    /* Refine */3,
    "refine"
  ],
  [
    /* Debug */4,
    "debug-gcl"
  ]
];

exports.names = names;
/* No side effect */
