// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var names = [
  /* tuple */[
    /* Reload */0,
    "reload"
  ],
  /* tuple */[
    /* Refine */1,
    "refine"
  ],
  /* tuple */[
    /* InsertAssertion */2,
    "insert-assertion"
  ],
  /* tuple */[
    /* Debug */3,
    "debug"
  ]
];

exports.names = names;
/* No side effect */
