// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var View$Guacamole = require("./View.bs.js");

function load(state) {
  console.log("load!");
  return View$Guacamole.activate(state);
}

exports.load = load;
/* View-Guacamole Not a pure module */
