// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(param) {
  return [
          "JSON Decode Error",
          param._0 + ("\nJSON from GCL: \n" + JSON.stringify(param._1))
        ];
}

exports.toString = toString;
/* No side effect */
