// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(msg) {
  if (msg.TAG) {
    return [
            "JSON Decode Error",
            msg._0 + ("\nJSON from GCL: \n" + JSON.stringify(msg._1))
          ];
  } else {
    return [
            "LSP Error",
            msg._0
          ];
  }
}

function fromJsError(error) {
  return (function (e) {return e.toString()})(error);
}

exports.toString = toString;
exports.fromJsError = fromJsError;
/* No side effect */
