// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function toString(param) {
  return /* tuple */[
          "JSON Decode Error",
          param[0] + ("\nJSON from GCL: \n" + JSON.stringify(param[1]))
        ];
}

exports.toString = toString;
/* No side effect */
