// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var State$Guacamole = require("./State.bs.js");
var TaskRunner$Guacamole = require("./Task/TaskRunner.bs.js");

var dict = {};

function get(fileName) {
  return Js_dict.get(dict, fileName);
}

function add(fileName, dispatcher) {
  var match = Js_dict.get(dict, fileName);
  if (match !== undefined) {
    return ;
  } else {
    dict[fileName] = dispatcher;
    return ;
  }
}

function rename(oldName, newName) {
  var delete_ = (function (dict, key) {delete dict[key]});
  return Belt_Option.forEach(Js_dict.get(dict, oldName), (function (state) {
                console.log("[ states ][ rename ]", oldName, newName);
                delete_(dict, oldName);
                return add(newName, state);
              }));
}

function remove(fileName) {
  var delete_ = (function (dict, key) {delete dict[key]});
  return delete_(dict, fileName);
}

function destroy(fileName) {
  return $$Promise.get(Belt_Option.mapWithDefault(Js_dict.get(dict, fileName), $$Promise.resolved(undefined), (function (param) {
                    var taskRunner = param[1];
                    console.log("[ states ][ destroy ]" + fileName);
                    return $$Promise.flatMap(State$Guacamole.destroy(param[0]), (function (param) {
                                  return TaskRunner$Guacamole.destroy(taskRunner);
                                }));
                  })), (function (param) {
                return remove(fileName);
              }));
}

function contains(fileName) {
  return Belt_Option.isSome(Js_dict.get(dict, fileName));
}

exports.dict = dict;
exports.get = get;
exports.add = add;
exports.rename = rename;
exports.remove = remove;
exports.destroy = destroy;
exports.contains = contains;
/* Promise Not a pure module */
