// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var GCL$Guacamole = require("./GCL.bs.js");

function encode(x) {
  if (typeof x === "number") {
    if (x === /* ExportProofObligations */0) {
      return Json_encode.object_({
                  hd: [
                    "tag",
                    "ReqExportProofObligations"
                  ],
                  tl: /* [] */0
                });
    } else {
      return Json_encode.object_({
                  hd: [
                    "tag",
                    "ReqDebug"
                  ],
                  tl: /* [] */0
                });
    }
  }
  switch (x.TAG | 0) {
    case /* Inspect */0 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqInspect"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple2((function (prim) {
                                return prim;
                              }), (function (prim) {
                                return prim;
                              }), [
                              x._0,
                              x._1
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Refine */1 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqRefine"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple2((function (prim) {
                                return prim;
                              }), (function (prim) {
                                return prim;
                              }), [
                              x._0,
                              x._1
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Substitute */2 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqSubstitute"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple3((function (prim) {
                                return prim;
                              }), GCL$Guacamole.Syntax.Expr.encode, (function (param) {
                                return Json_encode.array((function (param) {
                                              return Json_encode.pair(GCL$Guacamole.Syntax.Name.encode, GCL$Guacamole.Syntax.Expr.encode, param);
                                            }), param);
                              }), [
                              x._0,
                              x._1,
                              x._2
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    
  }
}

var Kind = {
  encode: encode
};

function encode$1(x) {
  return Json_encode.pair((function (prim) {
                return prim;
              }), encode, [
              x._0,
              x._1
            ]);
}

exports.Kind = Kind;
exports.encode = encode$1;
/* GCL-Guacamole Not a pure module */
