// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/lib/js/src/Json.bs.js");
var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function request(param) {
  if (typeof param === "number") {
    return Json_encode.object_(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                  /* tuple */[
                    "tag",
                    "ReqDebug"
                  ],
                  /* [] */0
                ]));
  } else {
    switch (param.tag | 0) {
      case /* Load */0 :
          var filepath = param[0];
          if (param[1]) {
            return Json_encode.object_(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                          /* tuple */[
                            "tag",
                            "ReqLoad"
                          ],
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              /* tuple */[
                                "contents",
                                Json_encode.pair((function (prim) {
                                        return prim;
                                      }), (function (prim) {
                                        return prim;
                                      }), /* tuple */[
                                      filepath,
                                      true
                                    ])
                              ],
                              /* [] */0
                            ])
                        ]));
          } else {
            return Json_encode.object_(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                          /* tuple */[
                            "tag",
                            "ReqLoad"
                          ],
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              /* tuple */[
                                "contents",
                                Json_encode.pair((function (prim) {
                                        return prim;
                                      }), (function (prim) {
                                        return prim;
                                      }), /* tuple */[
                                      filepath,
                                      false
                                    ])
                              ],
                              /* [] */0
                            ])
                        ]));
          }
      case /* Refine */1 :
          return Json_encode.object_(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                        /* tuple */[
                          "tag",
                          "ReqRefine"
                        ],
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            /* tuple */[
                              "contents",
                              Json_encode.pair((function (prim) {
                                      return prim;
                                    }), (function (prim) {
                                      return prim;
                                    }), /* tuple */[
                                    param[0],
                                    param[1]
                                  ])
                            ],
                            /* [] */0
                          ])
                      ]));
      case /* InsertAssertion */2 :
          return Json_encode.object_(/* :: */Caml_chrome_debugger.simpleVariant("::", [
                        /* tuple */[
                          "tag",
                          "ReqInsertAssertion"
                        ],
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            /* tuple */[
                              "contents",
                              param[0]
                            ],
                            /* [] */0
                          ])
                      ]));
      
    }
  }
}

var Encode = {
  request: request
};

function encode(x) {
  return Json.stringify(request(x));
}

exports.Encode = Encode;
exports.encode = encode;
/* No side effect */
