// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var GCL$Guacamole = require("./GCL.bs.js");

function request(filepath) {
  if (typeof filepath === "number") {
    return Json_encode.object_({
                hd: [
                  "tag",
                  "ReqDebug"
                ],
                tl: /* [] */0
              });
  }
  switch (filepath.TAG | 0) {
    case /* Load */0 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqLoad"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        filepath._0
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Refine */1 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqRefine"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple3((function (prim) {
                                return prim;
                              }), (function (prim) {
                                return prim;
                              }), (function (prim) {
                                return prim;
                              }), [
                              filepath._0,
                              filepath._1,
                              filepath._2
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* Substitute */2 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "ReqSubstitute"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        Json_encode.tuple4((function (prim) {
                                return prim;
                              }), (function (prim) {
                                return prim;
                              }), GCL$Guacamole.Syntax.Expr.encode, GCL$Guacamole.Syntax.Expr.encodeSubst, [
                              filepath._0,
                              filepath._1,
                              filepath._2,
                              filepath._3
                            ])
                      ],
                      tl: /* [] */0
                    }
                  });
    
  }
}

var Encode = {
  request: request
};

var encode = request;

exports.Encode = Encode;
exports.encode = encode;
/* GCL-Guacamole Not a pure module */
