// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var GCL$Guacamole = require("./GCL.bs.js");
var Util$Guacamole = require("./Util.bs.js");

function toString(param) {
  switch (param.TAG | 0) {
    case /* AtAbort */0 :
        return "Abort";
    case /* AtSkip */1 :
        return "Skip";
    case /* AtSpec */2 :
        return "Spec";
    case /* AtAssignment */3 :
        return "Assignment";
    case /* AtAssertion */4 :
        return "Assertion";
    case /* AtLoopInvariant */5 :
        return "Loop Invariant";
    case /* AtIf */6 :
        return "Conditional";
    case /* AtLoop */7 :
        return "Loop";
    case /* AtTermination */8 :
        return "Termination";
    case /* AtBoundDecrement */9 :
        return "Bound Decrement";
    
  }
}

function locOf(loc) {
  return loc._0;
}

var decode = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "AtAbort" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 0,
                                              _0: x,
                                              [Symbol.for("name")]: "AtAbort"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtAssertion" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 4,
                                              _0: x,
                                              [Symbol.for("name")]: "AtAssertion"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtAssignment" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 3,
                                              _0: x,
                                              [Symbol.for("name")]: "AtAssignment"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtBoundDecrement" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 9,
                                              _0: x,
                                              [Symbol.for("name")]: "AtBoundDecrement"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtIf" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 6,
                                              _0: x,
                                              [Symbol.for("name")]: "AtIf"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtLoop" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 7,
                                              _0: x,
                                              [Symbol.for("name")]: "AtLoop"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtLoopInvariant" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 5,
                                              _0: x,
                                              [Symbol.for("name")]: "AtLoopInvariant"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtSkip" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 1,
                                              _0: x,
                                              [Symbol.for("name")]: "AtSkip"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtSpec" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 2,
                                              _0: x,
                                              [Symbol.for("name")]: "AtSpec"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "AtTermination" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (x) {
                                      return {
                                              TAG: 8,
                                              _0: x,
                                              [Symbol.for("name")]: "AtTermination"
                                            };
                                    }), GCL$Guacamole.Loc.decode, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

function encode(loc) {
  switch (loc.TAG | 0) {
    case /* AtAbort */0 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtAbort"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtSkip */1 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtSkip"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtSpec */2 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtSpec"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtAssignment */3 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtAssignment"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtAssertion */4 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtAssertion"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtLoopInvariant */5 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtLoopInvariant"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtIf */6 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtIf"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtLoop */7 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtLoop"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtTermination */8 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtTermination"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    case /* AtBoundDecrement */9 :
        return Json_encode.object_({
                    hd: [
                      "tag",
                      "AtBoundDecrement"
                    ],
                    tl: {
                      hd: [
                        "contents",
                        GCL$Guacamole.Loc.encode(loc._0)
                      ],
                      tl: /* [] */0
                    }
                  });
    
  }
}

var Origin = {
  toString: toString,
  locOf: locOf,
  decode: decode,
  encode: encode
};

function decode$1(param) {
  return Json_decode.map((function (param) {
                return {
                        _0: param[0],
                        _1: param[1],
                        _2: param[2],
                        _3: param[3],
                        [Symbol.for("name")]: "ProofObligation"
                      };
              }), (function (param) {
                return Json_decode.tuple4(Json_decode.$$int, GCL$Guacamole.Syntax.Pred.decode, GCL$Guacamole.Syntax.Pred.decode, decode, param);
              }), param);
}

function encode$1(param) {
  return Json_encode.tuple4((function (prim) {
                return prim;
              }), GCL$Guacamole.Syntax.Pred.encode, GCL$Guacamole.Syntax.Pred.encode, encode, [
              param._0,
              param._1,
              param._2,
              param._3
            ]);
}

var ProofObligation = {
  decode: decode$1,
  encode: encode$1
};

function decode$2(json) {
  return {
          id: Json_decode.field("specID", Json_decode.$$int, json),
          pre: Json_decode.field("specPreCond", GCL$Guacamole.Syntax.Pred.decode, json),
          post: Json_decode.field("specPostCond", GCL$Guacamole.Syntax.Pred.decode, json),
          loc: Json_decode.field("specLoc", GCL$Guacamole.Loc.decode, json)
        };
}

var Specification = {
  decode: decode$2
};

var decode$3 = GCL$Guacamole.Syntax.Expr.decode;

var encode$2 = GCL$Guacamole.Syntax.Expr.encode;

var GlobalProp = {
  decode: decode$3,
  encode: encode$2
};

function toLoc(site, specifications) {
  if (!site.TAG) {
    return site._0;
  }
  var i = site._1;
  var loc = site._0;
  var specs = Belt_Array.keep(specifications, (function (spec) {
          return spec.id === i;
        }));
  return Belt_Option.mapWithDefault(Belt_Array.get(specs, 0), loc, (function (spec) {
                return GCL$Guacamole.Loc.translateBy(1, 0, 1, 0, GCL$Guacamole.Loc.translate(loc, spec.loc));
              }));
}

function toRange(site, specifications, locToRange) {
  return Curry._1(locToRange, toLoc(site, specifications));
}

function toString$1(site) {
  if (site.TAG) {
    return "at " + (GCL$Guacamole.Loc.toString(site._0) + (" in #" + String(site._1)));
  } else {
    return "at " + GCL$Guacamole.Loc.toString(site._0);
  }
}

var decode$4 = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "Global" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 0,
                                _0: Curry._1(GCL$Guacamole.Loc.decode, json),
                                [Symbol.for("name")]: "Global"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "Local" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 1,
                                              _0: param[0],
                                              _1: param[1],
                                              [Symbol.for("name")]: "Local"
                                            };
                                    }), (function (param) {
                                      return Json_decode.pair(GCL$Guacamole.Loc.decode, Json_decode.$$int, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

var Site = {
  toLoc: toLoc,
  toRange: toRange,
  toString: toString$1,
  decode: decode$4
};

var decode$5 = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "NotFunction" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 3,
                                              _0: param[0],
                                              [Symbol.for("name")]: "NotFunction"
                                            };
                                    }), (function (param) {
                                      return Json_decode.pair(GCL$Guacamole.Syntax.Type.decode, GCL$Guacamole.Loc.decode, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "NotInScope" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 0,
                                              _0: param[0],
                                              [Symbol.for("name")]: "NotInScope"
                                            };
                                    }), (function (param) {
                                      return Json_decode.pair(Json_decode.string, GCL$Guacamole.Loc.decode, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "RecursiveType" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 2,
                                              _0: param[0],
                                              _1: param[1],
                                              [Symbol.for("name")]: "RecursiveType"
                                            };
                                    }), (function (param) {
                                      return Json_decode.tuple3(Json_decode.$$int, GCL$Guacamole.Syntax.Type.decode, GCL$Guacamole.Loc.decode, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "UnifyFailed" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 1,
                                              _0: param[0],
                                              _1: param[1],
                                              [Symbol.for("name")]: "UnifyFailed"
                                            };
                                    }), (function (param) {
                                      return Json_decode.tuple3(GCL$Guacamole.Syntax.Type.decode, GCL$Guacamole.Syntax.Type.decode, GCL$Guacamole.Loc.decode, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

var $$TypeError = {
  decode: decode$5
};

var decode$6 = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "DigHole" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* DigHole */4;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "ExcessBound" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* ExcessBound */2;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingAssertion" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingAssertion */0;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingBound" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingBound */1;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingPostcondition" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingPostcondition */3;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

var StructError = {
  decode: decode$6
};

var decode$7 = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "DigHole" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* DigHole */5;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingBound" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingBound */1;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingLoopInvariant" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingLoopInvariant */0;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingPostcondition" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingPostcondition */3;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "MissingPrecondition" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* MissingPrecondition */2;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "PreconditionUnknown" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return /* PreconditionUnknown */4;
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

var StructError2 = {
  decode: decode$7
};

var decodeKind = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "CannotDecodeRequest" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 4,
                                _0: Json_decode.string(json),
                                [Symbol.for("name")]: "CannotDecodeRequest"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "CannotReadFile" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 5,
                                _0: Json_decode.string(json),
                                [Symbol.for("name")]: "CannotReadFile"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "LexicalError" :
            return {
                    TAG: 1,
                    _0: (function (param) {
                        return /* LexicalError */0;
                      }),
                    [Symbol.for("name")]: "TagOnly"
                  };
        case "NotLoaded" :
            return {
                    TAG: 1,
                    _0: (function (param) {
                        return /* NotLoaded */1;
                      }),
                    [Symbol.for("name")]: "TagOnly"
                  };
        case "StructError" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 1,
                                _0: Curry._1(decode$6, json),
                                [Symbol.for("name")]: "StructError"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "StructError2" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 2,
                                _0: Curry._1(decode$7, json),
                                [Symbol.for("name")]: "StructError2"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "SyntacticError" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (pairs) {
                                      return {
                                              TAG: 0,
                                              _0: Belt_Array.map(pairs, (function (prim) {
                                                      return prim[1];
                                                    })),
                                              [Symbol.for("name")]: "SyntacticError"
                                            };
                                    }), (function (param) {
                                      return Json_decode.array((function (param) {
                                                    return Json_decode.pair(GCL$Guacamole.Loc.decode, Json_decode.string, param);
                                                  }), param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "TypeError" :
            return {
                    TAG: 0,
                    _0: (function (json) {
                        return {
                                TAG: 3,
                                _0: Curry._1(decode$5, json),
                                [Symbol.for("name")]: "TypeError"
                              };
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

function decode$8(param) {
  return Json_decode.map((function (param) {
                return {
                        _0: param[0],
                        _1: param[1],
                        [Symbol.for("name")]: "Error"
                      };
              }), (function (param) {
                return Json_decode.pair(decode$4, decodeKind, param);
              }), param);
}

var $$Error = {
  Site: Site,
  $$TypeError: $$TypeError,
  StructError: StructError,
  StructError2: StructError2,
  decodeKind: decodeKind,
  decode: decode$8
};

var decode$9 = Util$Guacamole.Decode.sum(function (tag) {
      switch (tag) {
        case "ResError" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (errors) {
                                      return {
                                              TAG: 0,
                                              _0: errors,
                                              [Symbol.for("name")]: "Error"
                                            };
                                    }), (function (param) {
                                      return Json_decode.array(decode$8, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "ResOK" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 1,
                                              _0: param[0],
                                              _1: param[1],
                                              _2: param[2],
                                              _3: param[3],
                                              [Symbol.for("name")]: "OK"
                                            };
                                    }), (function (param) {
                                      return Json_decode.tuple4(Json_decode.$$int, (function (param) {
                                                    return Json_decode.array(decode$1, param);
                                                  }), (function (param) {
                                                    return Json_decode.array(decode$2, param);
                                                  }), (function (param) {
                                                    return Json_decode.array(decode$3, param);
                                                  }), param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "ResResolve" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (i) {
                                      return {
                                              TAG: 2,
                                              _0: i,
                                              [Symbol.for("name")]: "Resolve"
                                            };
                                    }), Json_decode.$$int, param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        case "ResSubstitute" :
            return {
                    TAG: 0,
                    _0: (function (param) {
                        return Json_decode.map((function (param) {
                                      return {
                                              TAG: 3,
                                              _0: param[0],
                                              _1: param[1],
                                              [Symbol.for("name")]: "Substitute"
                                            };
                                    }), (function (param) {
                                      return Json_decode.pair(Json_decode.$$int, GCL$Guacamole.Syntax.Expr.decode, param);
                                    }), param);
                      }),
                    [Symbol.for("name")]: "Contents"
                  };
        default:
          throw {
                RE_EXN_ID: Json_decode.DecodeError,
                _1: "Unknown constructor: " + tag,
                Error: new Error()
              };
      }
    });

exports.Origin = Origin;
exports.ProofObligation = ProofObligation;
exports.Specification = Specification;
exports.GlobalProp = GlobalProp;
exports.$$Error = $$Error;
exports.decode = decode$9;
/* decode Not a pure module */
