// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Sig$Guacamole = require("./Implementation/Sig.bs.js");
var Command$Guacamole = require("./Command.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");
var TaskRunner$Guacamole = require("./Task/TaskRunner.bs.js");
var Impl__State$Guacamole = require("./Implementation/Impl__State.bs.js");
var Task__Command$Guacamole = require("./Task/Task__Command.bs.js");

function Impl(Editor) {
  var State = Impl__State$Guacamole.Impl(Editor);
  var dict = { };
  var get = function (fileName) {
    return Js_dict.get(dict, fileName);
  };
  var getByEditor = function (editor) {
    return Belt_Option.flatMap(Curry._1(Editor.getFileName, editor), get);
  };
  var add = function (fileName, state) {
    var match = Js_dict.get(dict, fileName);
    if (match !== undefined) {
      return /* () */0;
    } else {
      console.log("[ states ][ add ]");
      dict[fileName] = state;
      return /* () */0;
    }
  };
  var rename = function (oldName, newName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return Belt_Option.forEach(Js_dict.get(dict, oldName), (function (state) {
                  console.log("[ states ][ rename ]", oldName, newName);
                  delete_(dict, oldName);
                  return add(newName, state);
                }));
  };
  var remove = function (fileName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return delete_(dict, fileName);
  };
  var destroy = function (fileName) {
    Belt_Option.forEach(Js_dict.get(dict, fileName), (function (state) {
            console.log("[ states ][ destroy ]");
            Curry._1(State.destroy, state);
            return /* () */0;
          }));
    return remove(fileName);
  };
  var contains = function (fileName) {
    return Belt_Option.isSome(Js_dict.get(dict, fileName));
  };
  var destroyAll = function (param) {
    Belt_Array.map(Js_dict.entries(dict), (function (param) {
            return Curry._1(State.destroy, param[1]);
          }));
    return /* () */0;
  };
  return {
          State: State,
          dict: dict,
          get: get,
          getByEditor: getByEditor,
          add: add,
          rename: rename,
          remove: remove,
          destroy: destroy,
          contains: contains,
          destroyAll: destroyAll
        };
}

var StateDict = {
  Impl: Impl
};

var partial_arg = /\.gcl$/i;

function isGCL(param) {
  return partial_arg.test(param);
}

function Impl$1(Editor) {
  var State = Impl__State$Guacamole.Impl(Editor);
  var dict = { };
  var get = function (fileName) {
    return Js_dict.get(dict, fileName);
  };
  var getByEditor = function (editor) {
    return Belt_Option.flatMap(Curry._1(Editor.getFileName, editor), get);
  };
  var add = function (fileName, state) {
    var match = Js_dict.get(dict, fileName);
    if (match !== undefined) {
      return /* () */0;
    } else {
      console.log("[ states ][ add ]");
      dict[fileName] = state;
      return /* () */0;
    }
  };
  var rename = function (oldName, newName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return Belt_Option.forEach(Js_dict.get(dict, oldName), (function (state) {
                  console.log("[ states ][ rename ]", oldName, newName);
                  delete_(dict, oldName);
                  return add(newName, state);
                }));
  };
  var remove = function (fileName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return delete_(dict, fileName);
  };
  var destroy = function (fileName) {
    Belt_Option.forEach(Js_dict.get(dict, fileName), (function (state) {
            console.log("[ states ][ destroy ]");
            Curry._1(State.destroy, state);
            return /* () */0;
          }));
    return remove(fileName);
  };
  var contains = function (fileName) {
    return Belt_Option.isSome(Js_dict.get(dict, fileName));
  };
  var destroyAll = function (param) {
    Belt_Array.map(Js_dict.entries(dict), (function (param) {
            return Curry._1(State.destroy, param[1]);
          }));
    return /* () */0;
  };
  var States = {
    State: State,
    dict: dict,
    get: get,
    getByEditor: getByEditor,
    add: add,
    rename: rename,
    remove: remove,
    destroy: destroy,
    contains: contains,
    destroyAll: destroyAll
  };
  var TaskCommand = Task__Command$Guacamole.Impl(Editor);
  var TaskRunner = TaskRunner$Guacamole.Impl(Editor);
  var State$1 = Impl__State$Guacamole.Impl(Editor);
  var addToSubscriptions = function (f, context) {
    context.subscriptions.push(f);
    return /* () */0;
  };
  var activate = function (context) {
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidCloseEditor, destroy), context);
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidChangeFileName, (function (oldName, newName) {
                return Belt_Option.forEach(oldName, (function (oldName) {
                              return Belt_Option.forEach(newName, (function (newName) {
                                            if (contains(oldName)) {
                                              if (isGCL(newName)) {
                                                return rename(oldName, newName);
                                              } else {
                                                return destroy(oldName);
                                              }
                                            } else {
                                              return 0;
                                            }
                                          }));
                            }));
              })), context);
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidChangeActivation, (function (prev, next) {
                Belt_Option.forEach(Belt_Option.flatMap(prev, get), State$1.hide);
                return Belt_Option.forEach(Belt_Option.flatMap(next, get), State$1.show);
              })), context);
    Curry._2(Editor.addToSubscriptions, Curry._2(Editor.registerCommand, "toggle", (function (editor) {
                return Belt_Option.forEach(Curry._1(Editor.getFileName, editor), (function (fileName) {
                              var match = get(fileName);
                              if (match !== undefined) {
                                return destroy(fileName);
                              } else {
                                var state = Curry._2(State$1.make, context, editor);
                                Curry._2(Editor.addToSubscriptions, Curry._2(State$1.onDestroy, state, (function (param) {
                                            return remove(fileName);
                                          })), context);
                                add(fileName, state);
                                return $$Promise.get(Curry._1(State$1.connect, state), (function (param) {
                                              if (param.tag) {
                                                var match = Sig$Guacamole.$$Error.toString(param[0]);
                                                Curry._2(TaskRunner.run, state, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                        /* Display */Caml_chrome_debugger.variant("Display", 6, [
                                                            /* Error */Caml_chrome_debugger.variant("Error", 1, [match[0]]),
                                                            /* Plain */Caml_chrome_debugger.variant("Plain", 1, [match[1]])
                                                          ]),
                                                        /* [] */0
                                                      ]));
                                                return /* () */0;
                                              } else {
                                                Curry._2(TaskRunner.run, state, Curry._1(TaskCommand.dispatch, /* Reload */0));
                                                return /* () */0;
                                              }
                                            }));
                              }
                            }));
              })), context);
    return Belt_Array.forEach(Command$Guacamole.names, (function (param) {
                  var command = param[0];
                  return Curry._2(Editor.addToSubscriptions, Curry._2(Editor.registerCommand, param[1], (function (editor) {
                                    return Belt_Option.forEach(getByEditor(editor), (function (state) {
                                                  Curry._2(TaskRunner.run, state, Curry._1(TaskCommand.dispatch, command));
                                                  return /* () */0;
                                                }));
                                  })), context);
                }));
  };
  var deactivate = function (param) {
    return destroyAll(/* () */0);
  };
  return {
          States: States,
          TaskCommand: TaskCommand,
          TaskRunner: TaskRunner,
          State: State$1,
          addToSubscriptions: addToSubscriptions,
          activate: activate,
          deactivate: deactivate
        };
}

exports.StateDict = StateDict;
exports.isGCL = isGCL;
exports.Impl = Impl$1;
/* Promise Not a pure module */
