// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function Impl(Editor) {
  return {
          make: Editor.createView,
          destroy: Editor.destroyView
        };
}

exports.Impl = Impl;
/* No side effect */
